# Generated by Django 4.1.1 on 2022-10-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0004_studentuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='mobile',
        ),
    ]
