# Generated by Django 4.1.1 on 2022-10-19 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0007_recruiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='company',
        ),
    ]
