# Generated by Django 4.1.1 on 2022-10-22 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0009_jobs_delete_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
    ]
